import esbuild from "esbuild";

const banner =
  "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD. DO NOT EDIT THIS FILE DIRECTLY. */";

const production = process.argv.includes("--production");
const watch = process.argv.includes("--watch");

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", "electron"],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: production
});

if (watch) {
  await context.watch();
} else {
  await context.rebuild();
  await context.dispose();
}
